version: '3'

services:
    #ca0:
    #  image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:ca-1.0-patched
    #  environment:
    #    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    #  ports:
    #    - 7054:7054
    #  command: fabric-ca-server start -b admin:adminpw
    #  container_name: ca0
    #  volumes:
    #    - ./fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
  
    #orderer0:
    #  container_name: orderer0
    #  image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:orderer-fed2efa
    #  ports:
    #    - 7050:7050
    #  volumes:
    #    - ./orderer:/etc/hyperledger/fabric

    #peer0:
    #  container_name: peer0
    #  image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:peer-fed2efa
    #  environment:
    #    - CORE_PEER_ID=peer0
    #    - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
    #    - CORE_PEER_ADDRESS=peer0:7051
    #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0:7051 
    #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
    #    - CORE_PEER_EVENTS_ADDRESS=peer0:7053
    #    - CORE_PEER_LOCALMSPID=Org1MSP 
    #    - CORE_PEER_GOSSIP_ORGLEADER=true 
    #    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock 
    #    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    #    - CORE_LOGGING_LEVEL=INFO
    #    - CORE_PEER_TLS_ENABLED=false
    #    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dockercompose_default
    #  ports:
    #    - 7051:7051
    #    - 7053:7053
    #  volumes:
    #    - /var/run/:/host/var/run/
    #    - ./peer0:/etc/hyperledger/fabric
    #  depends_on:
    #    - orderer0

    #peer2:
    #  container_name: peer2
    #  image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:peer-fed2efa
    #  environment:
    #    - CORE_PEER_ID=peer2
    #    - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
    #    - CORE_PEER_ADDRESS=peer2:8051
    #    - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2:8051 
    #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2:8051
    #    - CORE_PEER_EVENTS_ADDRESS=peer2:8053
    #    - CORE_PEER_LOCALMSPID=Org2MSP 
    #    - CORE_PEER_GOSSIP_ORGLEADER=true 
    #    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock 
    #    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
    #    - CORE_LOGGING_LEVEL=INFO
    #    - CORE_PEER_TLS_ENABLED=false
    #    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dockercompose_default
    #  ports:
    #    - 8051:8051
    #    - 8053:8053
    #  volumes:
    #    - /var/run/:/host/var/run/
    #    - ./peer2:/etc/hyperledger/fabric
    #  depends_on:
    #    - orderer0

    cconsole:
      container_name: chain-console
      image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:cconsole-361d5de
      environment:
        - FABRIC_CA_SERVER_URL=http://localhost:7054
        - FABRIC_ORDERER_ENDPOINT=grpc://localhost:7050
        - SPRING_DATASOURCE.URL=jdbc:mysql://localhost:3306/invoice
        - SPRING_DATASOURCE.USERNAME=root
        - SPRING_DATASOURCE.PASSWORD=root
      command: java -jar /opt/chain-console-1.0-alpha2.jar                          
      volumes:                             
        - /Users/liuruichao/tmp/chain-console-1.0-alpha2.jar:/opt/chain-console-1.0-alpha2.jar
      ports:
        - 9494:9494
