version: '2'

services:
  ca0:
    image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:ca-1.0-patched
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    command: fabric-ca-server start -b admin:adminpw
    container_name: ca0

  orderer0:
    container_name: orderer0
    image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:orderer-fed2efa
    ports:
      - 7050:7050

  cconsole:
    container_name: chain-console
    image: registry.cn-beijing.aliyuncs.com/lovetcn/fabric:cconsole-361d5de
    environment:
      - FABRIC_CA_SERVER_URL=http://ca0:7054
      - FABRIC_ORDERER_ENDPOINT=grpc://orderer0:7050
    command: java -jar chain-console/cconsole-1.0.jar
    ports:
      - 9494:9494
    depends_on:
      - ca0
      - orderer0
